version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - cd infra
      - terraform init
      - terraform plan -out=tfplan
      - terraform show -json tfplan > plan.json
      - jq '.' plan.json > plan.pretty.json
  post_build:
    commands:
      - echo "Uploading tfplan to S3..."
      - aws s3 cp tfplan s3://terraform-plan-review/tfplan
      - aws s3 cp plan.json s3://terraform-plan-review/plan.pretty.json
artifacts:
  files:
    - tfplan
    - plan.json
    - buildspec-terraform-apply.yml
